### ISSUE TITLE
cannot add new items in atlas space

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/kg-editor#39]
Dear KG-Team, I just realized that I cannot add a new item to any of the fields in the "**atlas**" space. 

Not sure if this is a bug or if it was assumed for now that items in the atlas space would not be edited within the KG Editor.

If the latter is the case: I would prefer making editing (new items or corrections of existing items) possible in the KG-Editor but only for a defined group of curators (most likely for now: me, Ulrike, Heidi, Stefan).

**Comment by olinux** [comment]
This should be solved now - I've created the group ("atlas-curators") which has owner rights on the space. The list of persons is now already added. I've also made you an administrator so you should be able to manage the members yourself.
