### ISSUE TITLE
datasetVersion label on tabs sometimes does not update to the saved "short name"

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/kg-editor#40]
Dear KG-Team, while entering some first datasetVersions I realized that the label on the tabs for the corresponding card does not always display/update to the saved "short name" of the datasetVersion, but displays the KG identifier. 

Reloading, or clicking on a card usually leads to the correct update and the dislplay of the "short name".

**Comment by olinux** [comment]
Thanks for reporting this. This is most probably a re-rendering issue and is tricky to reproduce, but we'll keep an eye on it and as soon as we found a scenario when it happens, we take care of it. If you can find a pattern of occurrence in the meantime, please do not hesitate to post it here.
